### ISSUE TITLE
Analysis Bug: Wing/Plane lift force is proportional to weight

### ISSUE THREAD

**Issue by Raviu56** [UweSchuster/Aeolus-AeroSketchPad#11]
Hello,
I've come to your software on youtube, giving it a trial I've found a serious analysis bug that lift force is proportional to flight condition weight which is physically wrong.

To reproduce the bug: see next comment

**Comment by Raviu56** [comment]
Pardon, incompletely submitted by mistake.
To reproduce the bug: 
1. open Aeolus software, Quick Start -> Examples -> Wings -> Airliner
2. Run analysis
3. Check lift in Results -> Aerodynamic loads, should be around 721e+3 Newtons
4. Go to Model -> Flight conditions, change weight to 500,000 N
5. Run analysis again
6.  Check lift in Results -> Aerodynamic loads,  would be around 500e+3 Newtons!!!

This is a really serious bug, but hopefully should be easy to solve.
Tested on last version 4.25

**Comment by UweSchuster** [comment]
Hi @Raviu56 . Thanks for your message. The analysis will solve for the AOA to achieve the required lift for steady flight. That is, **you can expect that Lift=weight** because the resulting AOA is different. It is not a bug, rather a feature.

**Comment by UweSchuster** [comment]
Also, please note that the underlying solver is based on potential flow (i.e. attached flow, no separation). You should therefore always do a sanity check whether the resulting Cl is actually physically possible
