### ISSUE TITLE
Never ending popup

### ISSUE THREAD

**Issue by j2l** [UweSchuster/Aeolus-AeroSketchPad#2]
I'm a Blender user and when I read in the tutorial `6kg * 9.81 = 58.9N` I tend to test if entering `weight time the gravity constant` could work as it works in Blender for any numerical field.

I shouldn't have done that in Aeolus because it raises a never ending pop-up alert that leads you to force stop Aeolus:
![Screenshot from 2022-03-27 18-53-24](https://user-images.githubusercontent.com/65325/160562954-185bcb01-1e7f-42c9-ab90-8a4d38d6accc.png)

BTW, as you can see it works fine on Linux with wine :wink:

**Comment by UweSchuster** [comment]
Thanks @j2l . I fixed this with the latest version 4.22. Download [here](https://www.aeolus-aero.com/asp/download/).
