### ISSUE TITLE
Weird inconsistent propeller results

### ISSUE THREAD

**Issue by Jaaaky** [UweSchuster/Aeolus-AeroSketchPad#7]
Hello,
Please find the attached 4 propeller files
Actually there are all the same prop but in Clockwise and CCW configuration, single and double blades for each.

On version 4.25, CW show different results from CCW on static - speed 0 - thrust and on 30m/s 
On left_2blades it shows negative thrust on static, while 1blade shows what seems normal results.
All tests does not show errors or warnings

[test_props.zip](https://github.com/AeolusAero/Aeolus-AeroSketchPad/files/9571800/test_props.zip)

I started with the same prop;
Modified RPM from negative to positive, setting all airfoils as inverted and reversed twist angles so converted it from CCW rotation to CW.

I've tested the same weird inconsistency with different airfoils and blade designs.

To reproduce the problem simply open the files run analysis and compare results.

**Comment by UweSchuster** [comment]
Thanks for bringing this up. I will look into it and get back to you soon

**Comment by Jaaaky** [comment]
A follow-up: On version 4.25

I've tried some different examples with different airfoils over the past few days;
Having data from actual model experiments - static and nearly static thrust/power -, and analyzing the same propellers in CW and CCW configurations - of course modifying geometry to be suitable for both cases:

I'd the following notes - it may help debugging the issue -:
1. Single blades with negative RPM shows the most realists thrust results, after manually doubling the numbers assuming 2blades is simply double 1blade, but power is far from being accurate
2. double blades positive RPM shows the most realist power results, but thrust is far from being accurate
3. having more than 1 blade on positive RPM propellers is showing more consistent results than negative rotating blades, thrust and power are reasonable increasing, while on negative rotation it shows no reasonable consistency when increasing blade number

Hope this can help,

**Comment by UweSchuster** [comment]
Thanks @Jaaaky for you continued support.

Would you be able to share the model and the expected results as a baseline to start debugging?

The propeller analysis was compared to experiment results where agreement was ok: [CR-19-13-RevA_Comparison of Aerodynamic Simulations with Wind Tunnel Results.pdf](https://github.com/AeolusAero/Aeolus-AeroSketchPad/files/9614973/CR-19-13-RevA_Comparison.of.Aerodynamic.Simulations.with.Wind.Tunnel.Results.pdf)

**Comment by UweSchuster** [comment]
Dear @Jaaaky: 

In your model the innermost (root) section has a pretty low pitch. 
![image](https://user-images.githubusercontent.com/47351070/221820442-cf716d4c-0f0f-4433-b190-59eaa3937ab9.png)

You can see the drop in thread pitch on the figure below.
![image](https://user-images.githubusercontent.com/47351070/221820689-b3910800-90ae-4664-8f14-cb10f504b47b.png)

A too low pitch leads to a strong influence of the wake shed by the preceding blade at the blade roots and in some cases causes numerical issues. The plot below shows the wake shed by both blade trailing edges. Again, the low root pitch causes the wake to travel in x at low speed, and the next blade is very close to the vortex filaments in the wake. 
![image](https://user-images.githubusercontent.com/47351070/221817252-61ef06c6-cf59-4c6b-adf1-1732a1bd3ad1.png)

### Solution
- Avoid very low thread pitch in your model

Also, i noticed you use a very small tip chord (1mm). I recommend keeping a certain minimum chord, as it will
- provide more robust results
- speed up the analysis significantly

So, to fix the model, i propose harmonizing the root pitch and increasing tip chord from 1mm to 5mm, which yields:
![image](https://user-images.githubusercontent.com/47351070/221824286-a400407b-a5d4-41f0-b141-44b8c1beeac1.png)

This should resolve the issue.

Thanks again and best regards!
Uwe
